namespace galactic;

// Data model for Galactic Spacefarer Adventure

entity Planets {
  key id        : String(26); // ULID
      name      : String(100);
      createdAt : Timestamp;
}

entity Departments {
  key id     : String(26);
      name   : String(100);
      planet : Association to Planets; // owns/operates within a planet (tenant)
}

entity Positions {
  key id         : String(26);
      title      : String(100);
      grade      : Integer;
      department : Association to Departments;
}

// This entity represents application users, not the same as Spacefarers. It is used for authentication and authorization.
// This is only for showcase purposes, in a real application you would use a proper identity provider
entity Users {
  key id          : String(26); // ULID for application users
      username    : String(100);
      email       : String(200);
      displayName : String(200);
      planet      : Association to Planets; // user's home planet (tenant)
      isAdmin     : Boolean default false;
      disabled    : Boolean default false;
      createdAt   : Timestamp;
      updatedAt   : Timestamp;
}

entity Spacefarers {
  key id                      : String(26); // ULID PK, auto-generated by service @before CREATE if omitted
      firstName               : String(100);
      lastName                : String(100);
      birthDate               : Date;
      email                   : String(200) not null;
      originPlanet            : Association to Planets; // narrative origin
      planet                  : Association to Planets not null; // tenant (enforced)
      department              : Association to Departments;
      position                : Association to Positions;
      stardustCollected       : Decimal(12, 2) default 0;
      wormholeNavigationSkill : Integer; // expected 0..100 (validate in handlers or DB)
      spacesuitColor          : String(30);
      active                  : Boolean default true;
      createdAt               : Timestamp @cds.on.insert : $now;
      createdBy               : Association to Users; // auto-set from authenticated user @before CREATE
      @odata.etag
      updatedAt               : Timestamp @cds.on.insert : $now @cds.on.update : $now;
      updatedBy               : Association to Users; // NOTE: not currently auto-populated by any handler
}

// Future entity for recording navigation attempts.
// It is currently not projected in srv/service.cds and is not editable through the API.
entity NavigationLog {
  key id         : String(26);
      spacefarer : Association to Spacefarers not null;
      route      : String(2000) not null;
      success    : Boolean not null;
      telemetry  : String(4000);
      timestamp  : Timestamp not null;
}
